name: deployment

on:
  workflow_dispatch:
  push:
    branches: [main]  
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download source and settings
      run: |
        wget http://sobereva.com/multiwfn/misc/Multiwfn_3.8_dev_src_Linux.zip
        unzip Multiwfn_3.8_dev_src_Linux.zip
        mv Multiwfn_3.8_dev_src_Linux/* . 
        rmdir Multiwfn_3.8_dev_src_Linux
        rm Multiwfn_3.8_dev_src_Linux.zip
        wget http://sobereva.com/multiwfn/misc/Multiwfn_3.8_dev_bin_Linux_noGUI.zip
        unzip -o -j Multiwfn_3.8_dev_bin_Linux_noGUI.zip Multiwfn_3.8_dev_bin_Linux_noGUI/{settings.ini,LICENSE.txt}
        rm Multiwfn_3.8_dev_bin_Linux_noGUI.zip

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: source_dist
        FOLDER: "."
