name: deployment

on:
  workflow_dispatch:
  push:
  # schedule:
  #   - cron:  '30 5,17 * * *'
  
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download source and settings
      run: |
        wget http://sobereva.com/multiwfn/misc/Multiwfn_3.8_dev_src_Linux.zip
        unzip Multiwfn_3.8_dev_src_Linux.zip
        mv Multiwfn_3.8_dev_src_Linux/* . 
        rmdir Multiwfn_3.8_dev_src_Linux
        rm Multiwfn_3.8_dev_src_Linux.zip
        wget http://sobereva.com/multiwfn/misc/Multiwfn_3.8_dev_bin_Linux_noGUI.zip
        unzip -j -o Multiwfn_3.8_dev_bin_Linux_noGUI.zip Multiwfn_3.8_dev_bin_Linux_noGUI/settings.ini
        rm Multiwfn_3.8_dev_bin_Linux_noGUI.zip

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: source_dist
        FOLDER: "."

    - name: Get tag name from date
      id: tag_name
      run: echo "::set-output name=date::$(date +'%y%m.%d')"        

    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: ${{ steps.tag_name.outputs.date }}